"""SQL execution + schema reflection.

The runner owns the transaction. It strips any standalone BEGIN/COMMIT/ROLLBACK
from migration SQL and wraps the whole migration in a single transaction, so
every migration (handwritten, autogenerated, dry-run, or applied) uses one code
path — on PostgreSQL and SQLite alike. Destructive migrations are blocked here
before any DB connection is opened.

`connect(url)` selects the backend from the URL scheme: SQLite URLs route to
the stdlib `sqlite3` backend; everything else uses psycopg via libpq. The
psycopg branch is spelled `psycopg.connect(...)` through this module's imported
`psycopg` so existing monkeypatching of `migrator.psycopg.connect` keeps working.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass
from typing import Any

import psycopg

from chozo import connection, safety
from chozo.discovery import Migration
from chozo.sqlite_backend import connect as sqlite_connect

_TX_CONTROL = re.compile(r"^\s*(BEGIN|COMMIT|ROLLBACK)\s*;\s*$", re.IGNORECASE | re.MULTILINE)


@dataclass
class MigrationResult:
    status: str  # "applied" | "failed" | "blocked"
    duration: float | None = None
    error: str | None = None


def strip_transaction_control(sql: str) -> str:
    return _TX_CONTROL.sub("", sql)


def connect(url: str) -> Any:
    """Open a connection to the backend selected by `url`'s scheme.

    The return type is `Any` so the runner stays backend-agnostic: both a
    psycopg `Connection` and `chozo.sqlite_backend.SqliteConnection` expose the
    context-manager + execute/commit/rollback surface the runner uses.
    """
    if connection.is_sqlite(url):
        return sqlite_connect(url)
    # Reach `psycopg.connect` via the module attribute so test monkeypatching of
    # `migrator.psycopg.connect` is honored.
    return psycopg.connect(connection.to_libpq(url))


def execute(url: str, migration: Migration, dry_run: bool = False) -> MigrationResult:
    """Execute a migration's UP SQL. Returns a MigrationResult."""
    script = strip_transaction_control(migration.up.read_text())

    if not dry_run:
        findings = safety.analyze(script)
        if findings:
            labels = ", ".join(f.label for f in findings)
            return MigrationResult(
                status="blocked",
                error=f"{migration.name} is destructive ({labels}); apply it by hand.",
            )

    t0 = time.perf_counter()
    try:
        with connect(url) as conn:
            # psycopg types query as LiteralString to encourage parameterization;
            # migration files are legitimately dynamic scripts, so we execute the
            # runtime string directly. The SQLite backend's `execute` accepts a
            # plain `str`, so the ignore only matters for the psycopg path.
            conn.execute(script)  # type: ignore[reportArgumentType]
            if dry_run:
                conn.rollback()
            else:
                conn.commit()
    except Exception as exc:
        return MigrationResult(status="failed", duration=time.perf_counter() - t0, error=str(exc))
    return MigrationResult(status="applied", duration=time.perf_counter() - t0)


def execute_down(url: str, migration: Migration, dry_run: bool = False) -> MigrationResult:
    """Execute a migration's DOWN SQL (rollback one migration)."""
    if not migration.has_down:
        return MigrationResult(
            status="blocked",
            error=f"{migration.name} has no down.sql — cannot roll back.",
        )
    assert migration.down is not None
    script = strip_transaction_control(migration.down.read_text())
    t0 = time.perf_counter()
    try:
        with connect(url) as conn:
            conn.execute(script)  # type: ignore[reportArgumentType]
            if dry_run:
                conn.rollback()
            else:
                conn.commit()
    except Exception as exc:
        return MigrationResult(status="failed", duration=time.perf_counter() - t0, error=str(exc))
    return MigrationResult(status="applied", duration=time.perf_counter() - t0)


def reflect(url: str) -> dict:
    """Reflect the live database schema as plain JSON for agents / `chozo inspect`."""
    from sqlalchemy import create_engine, inspect

    engine = create_engine(url)
    insp = inspect(engine)
    tables: dict[str, dict] = {}
    for table_name in insp.get_table_names():
        columns = []
        for col in insp.get_columns(table_name):
            columns.append(
                {
                    "name": col["name"],
                    "type": str(col["type"]),
                    "nullable": col.get("nullable", True),
                    "default": col.get("default"),
                    "primary_key": False,
                }
            )
        pk = insp.get_pk_constraint(table_name)
        pk_cols = set(pk.get("constrained_columns") or [])
        for col in columns:
            if col["name"] in pk_cols:
                col["primary_key"] = True
        tables[table_name] = {
            "columns": columns,
            "primary_key": list(pk_cols),
            "indexes": [
                {"name": idx["name"], "columns": idx["column_names"], "unique": bool(idx["unique"])}
                for idx in insp.get_indexes(table_name)
            ],
            "foreign_keys": [
                {
                    "name": fk["name"],
                    "constrained_columns": fk["constrained_columns"],
                    "referred_table": fk["referred_table"],
                    "referred_columns": fk["referred_columns"],
                }
                for fk in insp.get_foreign_keys(table_name)
            ],
        }
    engine.dispose()
    return {"tables": tables}
